export { default as Header } from "./Header";
export { default as Statistics } from "./Statistics";
export { default as SectionHeader } from "./SectionHeader";
export { default as SliderNavigation } from "./SliderNavigation";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
export { default as Course } from "./Course";
export { default as Instructor } from "./Instructor";
export { default as Blog } from "./Blog";
